export const Copy = {
  app: {
    name: "GoFlo",
  },

  onboarding: {
    pageOneTitle: "Reminders,\nYour Way!",
    cycleAligned: "Cycle-Aligned",
    cycleExample: "Day 14: Take Progestogen",
    cycleDetail: "Take 200mg at 9pm",
    dailyRhythm: "Daily Rhythm",
    dailyExample: "Oestrogen Gel",
    dailyDetail: "2 pump at 8am",
    setDays: "Set Days",
    setDaysExample: "Change Patch",
    setDaysDetail: "Every Monday & Thursday",
    now: "now",
    pageTwoTitle: "Hello,",
    namePrompt: "What should we call you?",
    nameExplanation: "We use your name to personalize your dashboard and notifications.",
  },

  common: {
    done: "Done",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    today: "Today",
    tomorrow: "Tomorrow",
    never: "Never",
    on: "On",
    after: "After",
    active: "Active",
    week: "Week",
    day: "Day",
    days: "days",
    occurrence: "occurrence",
    to: "to",
  },

  navigation: {
    today: "Today",
    reminders: "Reminders",
    more: "More",
    profile: "Profile",
    history: "History",
    newReminder: "New Reminder",
  },

  home: {
    welcomeTitle: "Welcome",
    welcomeText: "Create your first reminder to get started.",
    createReminderButton: "Create a reminder",
    todaysReminders: "TODAYS ACTIVE REMINDERS",
    upcoming: "UP COMING",
    unresolved: "PAST UNRESOLVED REMINDERS",
    statusActive: "Status: Active",
    takeButton: "TAKE",
    skipButton: "SKIP",
    snoozeButton: "SNOOZE",
    doneButton: "Done",
    checkHistory: "Check out your History",
    checkHistoryText: (count: number) => `You have ${count} unresolved reminders, check out your history to make sure you're on track`,
    noRemindersTitle: "No reminders yet",
    noRemindersSubtitle: "Create your first reminder to get started",
    notificationBannerTitle: "Notifications disabled",
    notificationBannerText: "Enable notifications to receive your reminders",
    notificationBannerButton: "ENABLE NOW",
    notificationsDisabled: "Notifications disabled",
    timeToday: (time: string) => `${time} today`,
    dateAtTime: (date: string, time: string) => `${date} at ${time}`,
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    unresolvedTitle: "Your attention is needed",
    unresolvedBody: "You have several unresolved reminders",
    unresolvedSubtext: "Check out your history to make sure you're on track.",
    viewHistory: "View History >",
  },

  createReminder: {
    headerTitle: "Create reminder",
    editHeaderTitle: "Edit reminder",
    namePlaceholder: "Name your reminder...",
    frequencyTitle: "Frequency",
    chooseOne: "CHOOSE ONE",
    cyclePill: "Cycle",
    intervalPill: "Interval",
    weekdaysPill: "Weekdays",
    cycleLength: "Cycle length",
    cycleLengthDescription: "Set to your prescribed therapeutic cycle or your average menstrual cycle length",
    dayRange: "Reminder Day Range",
    dayRangeDescription: "Reminder will trigger daily during this specific phase of your cycle.",
    fromDay: "START DAY",
    toDay: "END DAY",
    startDate: "Start date",
    startDateDescription: "This is either your therapeutic cycle start date or day 1 of your last bleed",
    details: "Details",
    cycleStart: "Cycle Start",
    start: "Start",
    selectDate: "Select a date",
    selectTime: "Select a time",
    repeatsEvery: "Repeats every:",
    daysUnit: "DAY(S)",
    daysLabel: "DAYS",
    repeatOn: "Repeat on:",
    remindMeAt: "Remind me at",
    addAnotherTime: "Add another time",
    doseNotes: "Dose notes",
    doseNotesPlaceholder: "Add some notes",
    notificationSound: "Notification sound",
    snoozeDuration: "Snooze Duration",
    endDate: "End date",
    saveButton: "Save Reminder",
    deleteReminder: "Delete Reminder",
  },

  soundSettings: {
    makeSomeNoise: "Make some noise",
    playsDefaultSound: "An alarm will sound until you dismiss the notification",
  },

  remindersScreen: {
    title: "Reminders",
    noRemindersTitle: "No Reminders Yet",
    noRemindersDescription: "Create your first reminder to get started with building good habits.",
    createReminderButton: "Create A Reminder",
    selectAll: "Select all",
    deselectAll: "Deselect all",
    deleteCount: (count: number) => `Delete (${count})`,
    deleteConfirmTitle: "Delete Reminders",
    deleteConfirmMessage: (count: number) => `Are you sure you want to delete ${count} reminder${count > 1 ? "s" : ""}?`,
  },

  reminderDetail: {
    reminderNotFound: "Reminder not found",
    notScheduled: "Not scheduled",
    customSchedule: "Custom schedule",
    cycleBasedLabel: "Cycle-Based",
    calendarBasedLabel: "Calendar-Based",
    scheduleSection: "Schedule",
    timeLabel: "Time",
    repeatLabel: "Repeat",
    nextOccurrenceLabel: "Next Occurrence",
    markAsComplete: "Mark as Complete",
    deleteReminder: "Delete Reminder",
    everyNDays: (days: number) => `Every ${days} day${days > 1 ? "s" : ""}`,
    everyDays: (daysStr: string) => `Every ${daysStr}`,
  },

  history: {
    title: "History",
    noHistoryTitle: "No History Yet",
    noHistoryDescription: "Your notification history will appear here once you start receiving reminders.",
  },

  more: {
    title: "Account",
    settingsSection: "GENERAL SETTINGS",
    historyTitle: "History",
    historySubtitle: "View past notifications",
    snoozeTitle: "Snooze Settings",
    snoozeSubtitle: "Configure snooze duration",
    alarmSoundsTitle: "Alarm Sounds",
    alarmSoundsSubtitle: "Choose notification sound",
    accountSection: "Account",
    freeTrialTitle: "Free Trial",
    freeTrialSubtitle: "30 days remaining in your trial period. Enjoy all premium features!",
    trialRemaining: (days: number) => `${days} days remaining in your trial period. Enjoy all premium features!`,
    activeBadge: "ACTIVE",
    profileTitle: "Profile",
    profileSubtitle: "Manage your account",
    emailTitle: "Email",
    emailNotSet: "Not set",
    signOutTitle: "Sign Out",
    aboutSection: "About",
    versionTitle: "Version",
  },

  profile: {
    title: "Profile",
    changePhoto: "Change Photo",
    personalInfoSection: "Personal Information",
    displayNameLabel: "Display Name",
    displayNamePlaceholder: "Enter your name",
    emailLabel: "Email Address",
    emailPlaceholder: "Enter your email",
    subscriptionSection: "Subscription",
    freeTrialTitle: "Free Trial",
    trialEndsMessage: "Your trial ends in 30 days. Upgrade to continue using all features.",
    viewPlans: "View Plans",
    saveChanges: "Save Changes",
  },

  snoozeSettings: {
    title: "Snooze settings",
    description: "Choose how long to snooze notifications when you tap the snooze button.",
    infoText: "When you snooze a notification, it will remind you again after ",
    saveButton: "Save Settings",
    hour: "hour",
    hours: "hours",
    min: "min",
  },

  alarmSounds: {
    title: "Alarm sound",
    description: "Choose the sound that will play when your reminders go off.",
    webNotice: "Sound preview is available in the Expo Go app on your device.",
    saveButton: "Save Selection",
    sounds: {
      morning_glory: "Morning Glory",
      birdsong: "Birdsong",
      marimba: "Marimba",
      xylophone: "Xylophone",
      alarm_clock: "Alarm Clock",
      soft_chimes: "Soft Chimes",
      piano: "Piano",
      harp: "Harp",
    },
  },

  emptyState: {
    noReminders: {
      title: "No Reminders Yet",
      description: "Create your first reminder to get started with building good habits.",
    },
    noHistory: {
      title: "No History Yet",
      description: "Your notification history will appear here once you start receiving reminders.",
    },
  },

  actionConfirmation: {
    taken: "Taken, Good job!",
    skipped: "Reminder Skipped",
    snoozed: (duration: string) => `Snoozed for ${duration}`,
    snoozeTip: "Tip: Durations can be amended in the app",
  },

  reprompt: {
    titlePrefix: "Reminder:",
  },

  offlineBuffer: {
    warningTitle: "Reminders pausing soon",
    warningBody: "While offline, we can only schedule a limited number of reminders ahead. Reconnect and open the app to continue.",
  },

  paywall: {
    title: "Upgrade to GoFlo Pro",
    subtitle: "Get the most out of your reminders",
    monthlyLabel: "Monthly",
    yearlyLabel: "Yearly",
    yearlyBadge: "Save 40%",
    perMonth: "/month",
    perYear: "/year",
    subscribeButton: "Subscribe",
    restoreButton: "Restore Purchases",
    features: [
      "Unlimited reminders",
      "Custom alarm sounds",
      "Advanced cycle tracking",
      "Extended history",
      "Priority support",
    ],
    termsNotice: "Payment will be charged to your App Store or Google Play account. Subscription automatically renews unless cancelled at least 24 hours before the end of the current period.",
    purchaseSuccess: "Welcome to GoFlo Pro!",
    purchaseError: "Something went wrong. Please try again.",
    restoreSuccess: "Purchases restored successfully!",
    restoreNoActive: "No active subscriptions found.",
    webNotice: "Subscriptions are available in the Expo Go app on your device.",
    loadingPlans: "Loading plans...",
    subscribedTitle: "You're a Pro!",
    subscribedMessage: "Thank you for supporting GoFlo. You have access to all features.",
    manageSubscription: "Manage Subscription",
  },

  errors: {
    reminderNotFound: "Reminder not found",
    failedToCreate: "Failed to create reminder",
    failedToUpdate: "Failed to update reminder",
    failedToDelete: "Failed to delete reminder",
  },
};
